# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-17 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description yet'),
            preserve_default=False,
        ),
    ]
